logging:
  level:
    com.example.carrotmarket: debug
    org.hibernate.SQL: debug


# Settings for local
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/dongnae?characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: qwe335577!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false

jwt:
  secret-key: 6B64DCA4EA2F53EDIKU9AAB215FE7
