logging:
  level:
    com.example.carrotmarket: debug
    org.hibernate.SQL: debug

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
---
# Settings for local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dongnae?characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: dongnae
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database: mysql
